apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\bins\kompose.exe convert -v
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: mongo-db
  name: mongo-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongo-db
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\bins\kompose.exe convert -v
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.network/app-net: "true"
        io.kompose.service: mongo-db
    spec:
      containers:
      - image: mongo
        imagePullPolicy: ""
        name: mongo-db-reactive
        ports:
        - containerPort: 27017
        - containerPort: 27018
        - containerPort: 27019
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
