apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\bins\kompose.exe convert -v
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: mongo-db
  name: mongo-db
spec:
  ports:
  - name: "27017"
    port: 27017
    targetPort: 27017
  - name: "27018"
    port: 27018
    targetPort: 27018
  - name: "27019"
    port: 27019
    targetPort: 27019
  selector:
    io.kompose.service: mongo-db
status:
  loadBalancer: {}
