apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\bins\kompose.exe convert -v
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: reactive-demo
  name: reactive-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: reactive-demo
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\bins\kompose.exe convert -v
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.network/app-net: "true"
        io.kompose.service: reactive-demo
    spec:
      containers:
      - image: reactive-comments
        imagePullPolicy: ""
        name: reactive-app
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
